//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProjects.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Tasks = new HashSet<Task>();
        }
    
        public int IdProject { get; set; }
        public string FullTitle { get; set; }
        public string ShortTitle { get; set; }
        public byte[] Icon { get; set; }
        public Nullable<System.TimeSpan> CreatedTime { get; set; }
        public Nullable<System.TimeSpan> DeletedTime { get; set; }
        public Nullable<System.DateTime> StartSheduleDate { get; set; }
        public Nullable<System.DateTime> FinishSheduleDate { get; set; }
        public string Description { get; set; }
        public int IdEmployee { get; set; }
        public int IdResponsible { get; set; }

        [JsonIgnore]
        public virtual User User { get; set; }
        [JsonIgnore]
        public virtual User User1 { get; set; }
        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks { get; set; }
    }
}
