//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProjects.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusStory
    {
        public int IdStatusStory { get; set; }
        public Nullable<int> IdTask { get; set; }
        public Nullable<int> IdOldStatus { get; set; }
        public Nullable<int> IdNewStatus { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual TaskStatu TaskStatu { get; set; }
        public virtual TaskStatu TaskStatu1 { get; set; }
    }
}
