//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiProjects.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Atachments = new HashSet<Atachment>();
            this.Inpectors = new HashSet<Inpector>();
            this.StatusStories = new HashSet<StatusStory>();
            this.Task1 = new HashSet<Task>();
        }
    
        public int IdTask { get; set; }
        public int ProjectId { get; set; }
        public string FullTitle { get; set; }
        public string ShortTitle { get; set; }
        public string Description { get; set; }
        public int ExecutiveEmployeeId { get; set; }
        public int StatusId { get; set; }
        public Nullable<System.TimeSpan> CreatedTime { get; set; }
        public Nullable<System.TimeSpan> UpdatedTime { get; set; }
        public Nullable<System.TimeSpan> DeletedTime { get; set; }
        public Nullable<System.DateTime> Deadline { get; set; }
        public Nullable<System.TimeSpan> StartActualTime { get; set; }
        public Nullable<System.TimeSpan> FinishActualTime { get; set; }
        public Nullable<int> PreviousTaskId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Atachment> Atachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Inpector> Inpectors { get; set; }
        [JsonIgnore]
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<StatusStory> StatusStories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Task> Task1 { get; set; }
        [JsonIgnore]
        public virtual Task Task2 { get; set; }
        [JsonIgnore]
        public virtual TaskStatu TaskStatu { get; set; }
        [JsonIgnore]
        public virtual User User { get; set; }
    }
}
